from .AccountPage import AccountPage
from .HomePage import HomePage
from .LoginPage import LoginPage
from .InstallPage import InstallPage
from .MainPage import MainPage
from .DownloadPage import DownloadPage
from .GameSettings import GameSettings
from .LauncherSettings import LauncherSettings
from .RegistrationPage import RegistrationPage
