from .MainPageUI import MainPageUI
from .LoginPageUI import LoginPageUI
from .BasePageUI import BasePageUI
from .HomePageUI import HomePageUI
from .AccountPageUI import AccountPageUI
from .DownloadPageUI import DownloadPageUI
from .GameSettingsUI import GameSettingsUI
from .LauncherSettingsUI import LauncherSettingsUI
from .RegistrationPageUI import RegistrationPageUI
from .LauncherUI import LauncherUI
