from .Page import Page
from .AccountPage import AccountPage
from .HomePage import HomePage
from .LoginPage import LoginPage
from .MainPage import MainPage
from .GameSettings import GameSettings
from .LauncherSettings import LauncherSettings
from .RegistrationPage import RegistrationPage
from .DownloadPage import DownloadPage
